#!/usr/bin/env python3
"""Generate a SeaBIOS C blob from a legally obtained IBM PC110 BIOS dump."""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

CLEAR = 0x100
END = 0x101
FIRST = 0x102


def read_code(src: bytes, bitpos: int, bits: int) -> tuple[int, int]:
    if bitpos + bits > len(src) * 8:
        return -1, bitpos
    bp = bitpos // 8
    off = bitpos & 7
    value = 0
    for i in range(3):
        if bp + i < len(src):
            value |= src[bp + i] << (8 * i)
    value >>= off
    return value & ((1 << bits) - 1), bitpos + bits


def expand(code: int, next_code: int, prefix: list[int], suffix: list[int]) -> list[int] | None:
    stack: list[int] = []
    while code >= 0x100:
        if code >= next_code or len(stack) >= 4096:
            return None
        stack.append(suffix[code])
        code = prefix[code]
    stack.append(code & 0xFF)
    return stack


def find_easysetup_stream(rom: bytes) -> tuple[bytes, int]:
    if len(rom) != 256 * 1024:
        raise SystemExit("error: expected a 256 KiB PC110 BIOS image")
    if not (rom[0] == 0x55 and rom[1] == 0xAA and rom[3] == 0xEB and rom[4] == 0x45):
        raise SystemExit("error: does not look like a PC110 BIOS image")

    src = rom[0x02BF:0x20000]
    out = bytearray()
    prefix = [0] * 4096
    suffix = [0] * 4096
    bits, next_code, grow_at, old, first, bitpos = 9, FIRST, 0x200, -1, 0, 0

    while True:
        code, bitpos = read_code(src, bitpos, bits)
        if code < 0:
            raise SystemExit(f"error: unexpected end at bitpos {bitpos}, out {len(out)}")
        if code == END:
            return src[: (bitpos + 7) // 8], len(out)
        if code == CLEAR:
            bits, next_code, grow_at, old = 9, FIRST, 0x200, -1
            code, bitpos = read_code(src, bitpos, bits)
            if code < 0 or code >= 0x100:
                raise SystemExit("error: bad clear code")
            out.append(code)
            old = first = code
            continue

        special = False
        if code < next_code:
            stack = expand(code, next_code, prefix, suffix)
        elif code == next_code and old >= 0:
            stack = expand(old, next_code, prefix, suffix)
            special = True
        else:
            raise SystemExit(f"error: bad code {code}/{next_code}")
        if stack is None:
            raise SystemExit("error: expand failed")

        cur_first = stack[-1]
        out.extend(reversed(stack))
        if special:
            out.append(first)
            cur_first = first
        if old >= 0 and next_code < 4096:
            prefix[next_code] = old
            suffix[next_code] = cur_first
            next_code += 1
            if next_code >= grow_at and bits < 12:
                bits += 1
                grow_at <<= 1
        old, first = code, cur_first


def write_c_blob(blob: bytes, decompressed_len: int, out_path: Path) -> None:
    digest = hashlib.sha256(blob).hexdigest()
    with out_path.open("w", encoding="ascii") as f:
        f.write("// Generated by scripts/extract-pc110-assets.py; do not commit IBM payload data.\n")
        f.write("#include \"types.h\"\n\n")
        f.write(f"// compressed={len(blob)} decompressed={decompressed_len} sha256={digest}\n")
        f.write(f"const u8 pc110_easysetup_lzw[{len(blob)}] = {{\n")
        for i in range(0, len(blob), 12):
            chunk = ", ".join(f"0x{b:02x}" for b in blob[i : i + 12])
            f.write(f"    {chunk},\n")
        f.write("};\n")
        f.write(f"const u32 pc110_easysetup_lzw_len = {len(blob)};\n")


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print("usage: extract-pc110-assets.py <pc110_bios.bin> <pc110_easysetup_blob.c>", file=sys.stderr)
        return 2
    rom = Path(argv[1]).read_bytes()
    blob, decompressed_len = find_easysetup_stream(rom)
    out_path = Path(argv[2])
    write_c_blob(blob, decompressed_len, out_path)
    print(f"wrote {out_path}: {len(blob)} compressed bytes, {decompressed_len} decompressed bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))

